alias ll="ls -hal"
alias pingtest="ping -c 3 8.8.8.8"
alias apt-get='sudo apt-get'
alias uu="apt-get update && apt-get upgrade -y"
alias open-folder="xdg-open"
alias open-image="eog"
alias ve='python3 -m venv ./venv'
alias va='source ./venv/bin/activate'
alias cls='clear'
alias wget='wget -c'
alias myip='curl ifconfig.me; echo'
alias reload='source ~/.bashrc'
alias bc='bc -l'
